---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      name: frontend-web
      labels:
        app: frontend-web
    spec:
      containers:
      - name: frontend-web
        image: stepanowon/frontend-web:1.0.0
        ports:
        - containerPort: 8000
      - name: nginx
        image: nginx
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: frontend-web
      port: 8000
      targetPort: 8000
    - name: nginx
      port: 80
      targetPort: 80
  selector:
    app: frontend-web
