---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-web
  template:
    metadata:
      name: backend-web
      labels:
        app: backend-web
    spec:
      containers:
      - name: backend-web
        image: stepanowon/backend-web:1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-web
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: backend-web
      port: 8080
      targetPort: 8080
  selector:
    app: backend-web
